absl-py == 2.1.0
accelerate == 0.31.0
actionlib == 1.14.0
angles == 1.9.13
appdirs == 1.4.4
argcomplete == 3.3.0
array_record == 0.5.1
asttokens == 2.4.1
astunparse == 1.6.3
attrdict == 2.0.1
bcrypt == 4.1.2
bondpy == 1.8.6
cachetools == 5.3.3
catkin == 0.8.10
catkin-pkg == 1.0.0
catkin-tools == 0.9.4
certifi == 2024.2.2
cffi == 1.16.0
cfgv == 3.4.0
charset-normalizer == 3.3.2
chex == 0.1.85
click == 8.1.7
cloudpickle == 3.0.0
colcon-argcomplete == 0.3.3
colcon-bash == 0.5.0
colcon-cd == 0.1.1
colcon-cmake == 0.2.28
colcon-common-extensions == 0.3.0
colcon-core == 0.16.0
colcon-defaults == 0.2.8
colcon-devtools == 0.3.0
colcon-library-path == 0.2.1
colcon-metadata == 0.2.5
colcon-output == 0.2.13
colcon-package-information == 0.4.0
colcon-package-selection == 0.2.10
colcon-parallel-executor == 0.2.4
colcon-pkg-config == 0.1.0
colcon-powershell == 0.4.0
colcon-python-setup-py == 0.2.7
colcon-recursive-crawl == 0.2.3
colcon-ros == 0.4.1
colcon-test-result == 0.3.8
colcon-zsh == 0.5.0
colorama == 0.4.6
coloredlogs == 15.0.1
comm == 0.2.2
contextlib2 == 21.6.0
contourpy == 1.2.1
coverage == 7.5.0
cryptography == 42.0.5
cv_bridge == 1.16.2
cycler == 0.12.1
debugpy == 1.8.1
decorator == 4.4.2
defusedxml == 0.7.1
diagnostic_analysis == 1.11.0
diagnostic_common_diagnostics == 1.11.0
diagnostic_updater == 1.11.0
distlib == 0.3.8
distrax == 0.1.5
distro == 1.9.0
dlimp == 0.0.1
dm-control == 1.0.14
dm-env == 1.6
dm-reverb == 0.14.0
dm-tree == 0.1.8
docker-pycreds == 0.4.0
docutils == 0.21.2
dynamic_reconfigure == 1.7.3
einops == 0.8.0
empy == 3.3.4
etils == 1.8.0
exceptiongroup == 1.2.0
executing == 2.0.1
filelock == 3.14.0
flash-attn == 2.5.9.post1
flatbuffers == 24.3.25
flax == 0.7.5
fonttools == 4.51.0
fsspec == 2024.3.1
gast == 0.5.4
gencpp == 0.7.0
geneus == 3.0.0
genlisp == 0.4.18
genmsg == 0.6.0
gennodejs == 2.0.2
genpy == 0.6.15
gitdb == 4.0.11
GitPython == 3.1.43
glfw == 2.7.0
google-auth == 2.29.0
google-auth-oauthlib == 1.2.0
google-pasta == 0.2.0
googleapis-common-protos == 1.63.0
grpcio == 1.63.0
gym == 0.26.2
gym-notices == 0.0.8
h5py == 3.11.0
huggingface-hub == 0.22.2
humanfriendly == 10.0
identify == 2.5.36
idna == 3.7
imageio == 2.34.1
imageio-ffmpeg == 0.4.9
importlib_metadata == 7.1.0
importlib_resources == 6.4.0
iniconfig == 2.0.0
interactive_markers == 1.12.0
ipykernel == 6.29.3
ipython == 8.22.2
jax == 0.4.20
jaxlib == 0.4.20+cuda11.cudnn86
jedi == 0.19.1
Jinja2 == 3.1.3
joblib == 1.4.2
joint_state_publisher == 1.15.1
joint_state_publisher_gui == 1.15.1
jupyter_client == 8.6.1
jupyter_core == 5.7.2
keras == 2.15.0
kiwisolver == 1.4.5
labmaze == 1.0.6
laser_geometry == 1.6.7
libclang == 18.1.1
lxml == 5.2.1
lz4 == 4.3.3
Markdown == 3.6
markdown-it-py == 3.0.0
MarkupSafe == 2.1.5
matplotlib == 3.8.4
matplotlib-inline == 0.1.7
mdurl == 0.1.2
mediapy == 1.2.0
message_filters == 1.16.0
ml_collections == 0.1.1
ml-dtypes == 0.4.0
moviepy == 1.0.3
mpmath == 1.3.0
msgpack == 1.0.8
mujoco == 2.3.7
munkres == 1.1.4
nest_asyncio == 1.6.0
netifaces == 0.11.0
networkx == 3.3
nodeenv == 1.8.0
nose == 1.3.7
numpy == 1.24.3
nvidia-cublas-cu11 == 11.11.3.6
nvidia-cublas-cu12 == 12.5.2.13
nvidia-cuda-cupti-cu11 == 11.8.87
nvidia-cuda-cupti-cu12 == 12.5.39
nvidia-cuda-nvcc-cu11 == 11.8.89
nvidia-cuda-nvcc-cu12 == 12.5.40
nvidia-cuda-nvrtc-cu11 == 11.8.89
nvidia-cuda-runtime-cu11 == 11.8.89
nvidia-cuda-runtime-cu12 == 12.5.39
nvidia-cudnn-cu11 == 8.7.0.84
nvidia-cudnn-cu12 == 9.1.1.17
nvidia-cufft-cu11 == 10.9.0.58
nvidia-cufft-cu12 == 11.2.3.18
nvidia-curand-cu11 == 10.3.0.86
nvidia-cusolver-cu11 == 11.4.1.48
nvidia-cusolver-cu12 == 11.6.2.40
nvidia-cusparse-cu11 == 11.7.5.86
nvidia-cusparse-cu12 == 12.4.1.24
nvidia-nccl-cu11 == 2.20.5
nvidia-nccl-cu12 == 2.21.5
nvidia-nvjitlink-cu12 == 12.5.40
nvidia-nvtx-cu11 == 11.8.86
oauthlib == 3.2.2
opencv-python == 4.9.0
opencv-python-headless == 4.9.0
OpenEXR == 3.2.4
opt-einsum == 3.3.0
optax == 0.1.5
orbax-checkpoint == 0.4.4
osrf-pycommon == 0.2.1
packaging == 24.0
pandas == 2.2.2
paramiko == 3.4.0
parso == 0.8.4
pexpect == 4.9.0
pickleshare == 0.7.5
pillow == 10.3.0
pip == 24.0
platformdirs == 4.2.1
plotly == 5.21.0
pluggy == 1.5.0
ply == 3.11
portpicker == 1.6.0
pre-commit == 3.3.3
proglog == 0.1.10
promise == 2.3
prompt-toolkit == 3.0.42
protobuf == 4.25.3
psutil == 5.9.8
ptyprocess == 0.7.0
pure-eval == 0.2.2
pyasn1 == 0.6.0
pyasn1_modules == 0.4.0
pybind11 == 2.12.0
pybind11_global == 2.12.0
pycairo == 1.26.0
pycparser == 2.22
pycryptodome == 3.20.0
pycryptodomex == 3.19.0
pydot == 2.0.0
Pygments == 2.17.2
PyNaCl == 1.5.0
PyOpenGL == 3.1.6
pyparsing == 3.1.2
PyQt-builder == 1.15.4
PyQt5 == 5.15.9
PyQt5-sip == 12.12.2
PyQtWebEngine == 5.15.4
pyrealsense2 == 2.55.1.6486
pytest == 8.2.0
pytest-cov == 5.0.0
pytest-repeat == 0.9.2
pytest-rerunfailures == 14.0
python-dateutil == 2.9.0
python-gnupg == 0.5.0
python_qt_binding == 0.4.4
pytz == 2024.1
PyYAML == 6.0.1
pyzmq == 26.0.2
qt_dotgraph == 0.4.2
qt_gui == 0.4.2
qt_gui_cpp == 0.4.2
qt_gui_py_common == 0.4.2
regex == 2024.4.28
requests == 2.31.0
requests-oauthlib == 2.0.0
resource_retriever == 1.12.7
rich == 13.7.1
rlds == 0.1.8
rosbag == 1.16.0
rosboost_cfg == 1.15.8
rosclean == 1.15.8
roscreate == 1.15.8
rosdep == 0.23.0
rosdistro == 0.9.0
rosgraph == 1.16.0
roslaunch == 1.16.0
roslib == 1.15.8
roslint == 0.12.0
roslz4 == 1.16.0
rosmake == 1.15.8
rosmaster == 1.16.0
rosmsg == 1.16.0
rosnode == 1.16.0
rosparam == 1.16.0
rospkg == 1.5.1
rospy == 1.16.0
rosservice == 1.16.0
rostest == 1.16.0
rostopic == 1.16.0
rosunit == 1.15.8
roswtf == 1.16.0
rqt_action == 0.4.9
rqt_bag == 0.5.1
rqt_bag_plugins == 0.5.1
rqt_console == 0.4.12
rqt_dep == 0.4.12
rqt_graph == 0.4.14
rqt_gui == 0.5.3
rqt_gui_py == 0.5.3
rqt_image_view == 0.4.17
rqt_launch == 0.4.9
rqt_logger_level == 0.4.12
rqt_moveit == 0.5.11
rqt_msg == 0.4.10
rqt_nav_view == 0.5.7
rqt_plot == 0.4.13
rqt_pose_view == 0.5.11
rqt_publisher == 0.4.10
rqt_py_common == 0.5.3
rqt_py_console == 0.4.10
rqt_reconfigure == 0.5.5
rqt_robot_dashboard == 0.5.8
rqt_robot_monitor == 0.5.15
rqt_robot_steering == 0.5.12
rqt_runtime_monitor == 0.5.10
rqt_rviz == 0.7.0
rqt_service_caller == 0.4.10
rqt_shell == 0.4.11
rqt_srv == 0.4.9
rqt_tf_tree == 0.6.4
rqt_top == 0.4.10
rqt_topic == 0.4.13
rqt_web == 0.4.10
rsa == 4.9
rviz == 1.14.20
safetensors == 0.4.3
scikit-learn == 1.5.0
scipy == 1.10.0
sensor_msgs == 1.13.1
sentry-sdk == 2.0.1
setproctitle == 1.3.3
setuptools == 69.5.1
sip == 6.7.12
six == 1.16.0
smach == 2.5.2
smach_ros == 2.5.2
smclib == 1.8.6
smmap == 5.0.1
stack-data == 0.6.2
sympy == 1.12
tenacity == 8.2.3
tensorboard == 2.15.2
tensorboard-data-server == 0.7.2
tensorflow == 2.15.0
tensorflow-addons == 0.23.0
tensorflow-datasets == 4.9.2
tensorflow-estimator == 2.15.0
tensorflow-graphics == 2021.12.3
tensorflow-hub == 0.16.1
tensorflow-io-gcs-filesystem == 0.37.0
tensorflow-metadata == 1.15.0
tensorflow-probability == 0.23.0
tensorflow-text == 2.15.0
tensorstore == 0.1.45
termcolor == 2.4.0
tf == 1.13.2
tf_conversions == 1.13.2
tf_keras == 2.15.1
tf2_geometry_msgs == 0.7.7
tf2_kdl == 0.7.7
tf2_py == 0.7.7
tf2_ros == 0.7.7
threadpoolctl == 3.5.0
timm == 0.9.10
tokenizers == 0.19.1
toml == 0.10.2
tomli == 2.0.1
toolz == 0.12.1
topic_tools == 1.16.0
torch == 2.3.1+cu118
torchaudio == 2.3.1+cu118
torchvision == 0.18.1+cu118
tornado == 6.4
tqdm == 4.66.2
traitlets == 5.14.3
transformations == 2024.4.24
transformers == 4.40.1
trimesh == 4.3.2
triton == 2.3.1
typeguard == 2.13.3
typing_extensions == 4.11.0
tzdata == 2024.1
urllib3 == 2.2.1
virtualenv == 20.26.1
wandb == 0.16.6
wcwidth == 0.2.13
Werkzeug == 3.0.2
wheel == 0.43.0
wrapt == 1.14.1
xacro == 1.14.17
zipp == 3.17.0